### ISSUE TITLE
Registration.py script

### ISSUE THREAD

**Issue by GaelKBertrand** [vkola-lab/brain2020#12]
In the registration.py script, line 31, you called a script labeled **'bash registration.sh'** However, such a script doesn't exist on this repository. There exists '**registration.sh'** 

Was any misunderstanding or mistake in this?

**Comment by shangranq** [comment]
hey as you mentioned There exists 'registration.sh' at https://github.com/vkola-lab/brain2020/blob/master/Data_Preprocess/registration.sh. "bash bashscript.sh" is just like "python pythonscript.py" which is what you need to type into the terminal to run the bash script
