### ISSUE TITLE
Registration in Shell

### ISSUE THREAD

**Issue by GaelKBertrand** [vkola-lab/brain2020#13]
By stating that $2 is the filename of the raw data, how is one supposed to be defining this variable? I suppose I can't put one single file name since this script is meant to run in a loop.

**Comment by shangranq** [comment]
$1, $2, etc are just arguments that you can pass into the script though terminal. If you want to process a single case, you can directly run the bash script in the terminal with the specific filename that you want to process as one of the argument. The filename you typed in the terminal will be recognized and parsed by the bash script. If you want to process a batch, you can use the python script which contains a loop. During looping, we are calling the bash script within the python process. In this case, $2 is defined by the python variable that you used to save the filename.
