### ISSUE TITLE
Working with the Inference Method

### ISSUE THREAD

**Issue by GaelKBertrand** [vkola-lab/brain2020#14]
The training phase was superb. I would like to ask more about the inference method. Earlier you have mentioned that one can use the 'model wrapper.py'  to work with the inference method. I would like to go further and save the model and maybe deploy it. Do you have any suggestions on how I can save the model using the scripts in the 'model wrapper.py'?

**Comment by shangranq** [comment]
hi, the model weights will be automatically saved in the checkpoint_dir folder.

**Comment by GaelKBertrand** [comment]
The data uploaded in "dataloader" using inference, does it have to be pre-processed according to your pre-processing method?
