### ISSUE TITLE
why the demor is defined through this 

### ISSUE THREAD

**Issue by WSW55** [vkola-lab/brain2020#25]
dear author，I really need your help！I try to use MLP_B in your code on my dataset ,but I can't understand the definition of the demor in the dataloader's MLP_Data. demor = [(demor[0]-70.0)/10.0] + gender + [(demor[2]-27)/2], what is it mean?  thanks very much!

**Comment by shangranq** [comment]
Hi, demor[0] is the numerical feature for age. [(demor[0]-70.0)/10.0] is normalizing the age by firstly subtracting the mean and then divided by the standard deviation. Similarly demor[2] is the numerical score of MMSE.
