### ISSUE TITLE
May I ask you to introduce the part of the 'Data_preprocess' briefly?

### ISSUE THREAD

**Issue by WillyPKU** [vkola-lab/brain2020#4]
Hello~  I've followed your work recently, but I'm confused about the MRI data preprocessing according to your code of the 'Data_preprocess'. Can you introduce this part briefly in the readme file? It will be greatly appreciated.

**Comment by shangranq** [comment]
Hey WillyPKU, Thanks for reaching out! I just re-organized the data preprocessing code and also described the usage in readme. Please let us know if you have any questions. Thanks!
