### ISSUE TITLE
IndexError: index 179 is out of bounds for axis 0 with size 170

### ISSUE THREAD

**Issue by WillyPKU** [vkola-lab/brain2020#5]
Thanks for your sharing~ I've met trouble when I followed the script for background removal, it appeared the error as follows: 
  0%|                                                                                      | 0/2292 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "back_remove.py", line 54, in <module>
    back_remove(file, temp, '/data/charlen/ADNI/ANDI_remove/')
  File "back_remove.py", line 32, in back_remove
    and data[new_x, new_y, new_z] < -0.6 and temp[new_x, new_y, new_z] < 0.8:
IndexError: index 179 is out of bounds for axis 0 with size 170

**Comment by shangranq** [comment]
you scan axis 0 size is 170 which is different from the template. Please double check the input size of the background removal step. My script only runs on scans with MNI template size, if you want to apply this step on input with other sizes, you need to customize the script.
