### ISSUE TITLE
Testing / inferring my own dataset using pre-trained FCN and MLP models

### ISSUE THREAD

**Issue by mitezo** [vkola-lab/brain2020#6]
Thank you for providing python scripts for your Brain 2020 paper.
I analyzed ADNI and AIBL data with the scripts and tested, validated, and tested models and obtained results similar to your paper.
I would like to run the scripts only to INFER my data rather than TRAIN and VALIDATE using the already trained FCN and MLP models.
Would you please tell me how to do that?

**Comment by shangranq** [comment]
Hi, my understanding is you want to do the inference on your own dataset using the pre-trained weights. The inference is a two steps process, i.e., FCN model inference and MLP model inference. (a) firstly about FCN inference, you can use the FCN_Wrapper class in the model_wrapper.py, "test_and_generate_DPMs" method in the FCN_Wrapper class allows you to do inference, the only thing you need to do is to replace the dataloader defined inside the method with your own dataloader. (about how to create dataloader, see dataloader.py). The inference result would be a set of 3D probability maps. (b) then you will run MLP on those 3D probablity maps to get final global diagnostic results.

**Comment by mitezo** [comment]
Thank you so much for your advise. I could do the inference on my own dataset.

**Comment by GaelKBertrand** [comment]
@mitezo, it's nice to hear that you have made some progress on this. Is it possible to get your contact so that I can reach out to you to figure out some of the challenges I am facing when training this?
