### ISSUE TITLE
Data Management 

### ISSUE THREAD

**Issue by GaelKBertrand** [vkola-lab/brain2020#9]
It would be helpful if you can extend the data preprocessing section and include a small point on data directories and where to edit the 'data path' 'them in the provided scripts. ADNI or other data sources tend to have some data organized in a way that doesn't allow the 'Dataloader.py' script to load it directly without some work done on reorganizing the data. This can save time for people conducting the training.

**Comment by shangranq** [comment]
if you decide to save the data in another folder, to use the dataloader.py, you can adjust the config.json file and adjust the folder to your customized folder. Yes, the raw data from ADNI or other sources might be organized in various ways, we are expecting the user to store the processed MRI data where a data folder directly contain numpy arrays in the corresponding folders specified in the config.json.
